#!/usr/bin/python3
print('<load-state xmlns="urn:lsi:params:xml:ns:yang:ivi-load">')
print('<channel><name>out1</name><measurement><voltage>0</voltage><current>0</current></measurement></channel>')
print('</load-state>')
