#!/usr/bin/python3
import sys
import vxi11

instr = vxi11.vxi11.Instrument(sys.argv[1])

try:
    reply = instr.ask("MEAS:CURR?")
except:
    reply = 0

current = float(reply)
current = format(current, ".9f")

try:
    reply = instr.ask("MEAS:VOLT?")
except:
    reply = 0
    
voltage = float(reply)
voltage = format(voltage, ".9f")


print('<load-state xmlns="urn:lsi:params:xml:ns:yang:ivi-load">')
print(
    f"<channel><name>out1</name><measurement><voltage>{voltage}</voltage><current>{current}</current></measurement></channel>"
)
print("</load-state>")
