#!/usr/bin/python3
import vxi11

instr = vxi11.vxi11.Instrument("TCPIP::localhost::gpib,5::INSTR")

reply = instr.ask("MEAS:CURR?")

current = float(reply)
current = format(current, ".9f")

reply = instr.ask("MEAS:VOLT?")

voltage = float(reply)
voltage = format(voltage, ".9f")

print('<load-state xmlns="urn:lsi:params:xml:ns:yang:ivi-load">')
print(
    f"<channel><name>out1</name><measurement><voltage>{voltage}</voltage><current>{current}</current></measurement></channel>"
)
print("</load-state>")
