#!/usr/bin/python3
import sys

import vxi11

instr = vxi11.vxi11.Instrument("TCPIP::localhost::gpib,5::INSTR")

instr.write('MODE:RES')
instr.write(f'INPUT {sys.argv[1].upper()}')
instr.write(f'RES {sys.argv[2]}')
