#!/usr/bin/python3
import sys

import vxi11

instr = vxi11.vxi11.Instrument("TCPIP::localhost::gpib,5::INSTR")
# instr = vxi11.vxi11.Instrument("TCPIP::10.0.0.8::gpib,5::INSTR")

instr.write("MODE:RES")
instr.write(f"INPUT {sys.argv[1].upper()}")
instr.write(f"RES {sys.argv[2]}")

if len(sys.argv) <= 3 and sys.argv[1].upper() != "OFF":
    instr.write(f"RES:TLEV  {sys.argv[3]}")

if len(sys.argv) <= 4 and sys.argv[1].upper() != "OFF":
    instr.write(f"TRAN:FREQ  {sys.argv[4]}")
    if sys.argv[3] < 0:
        print("yeeet")
        instr.write("TRAN:MODE CONT")
        instr.write("TRAN:DCYC 50")
        instr.write("TRAN ON")
    else:
        instr.write("TRAN OFF")
else:
    instr.write("TRAN OFF")

if sys.argv[1].upper() == "OFF":
    instr.write("TRAN OFF")
