#!/usr/bin/python3
import sys
from eastTester import eastTester

t1 = eastTester()
print(t1.system_beep())
print(t1.set_channel(1))
print(t1.ch_mode('CR'))
print(t1.resi_cr(sys.argv[2]))
print(t1.ch_switch(sys.argv[1]))

print(t1.set_channel(2))
print(t1.ch_mode('CR'))
print(t1.resi_cr(sys.argv[4]))
print(t1.ch_switch(sys.argv[3]))
